### ISSUE TITLE
Opprette SOPS config og generee default RoS

### ISSUE THREAD

**Issue by larsore** [kartverket/backstage-plugin-risk-scorecard-backend#267]
**Is your feature request related to a problem? Please describe.**
Jeg blir frustrert når det å starte med kodenær ROS er så vanskelig på egenhånd. 

```[tasklist]
### Tasks
- [x] Få første SOPS-config inn på main i et repo uten RoS
- [x] Skal kun få velge mellom prod-prosjekter
- [x] Skal kunne oppdatere SOPS config i en branch
- [x] Default ROS-en må vises i plugin etter at den er opprettet uten at brukeren må refreshe siden
- [x] https://github.com/kartverket/backstage-plugin-risk-scorecard-backend/issues/268
- [ ] https://github.com/kartverket/backstage-plugin-risk-scorecard-backend/issues/263
```
